language: ruby
sudo: false
services: mongodb
rvm:
  - "2.1.10"
  - "2.2.4"
  - "2.3.0"
gemfile:
  - gemfiles/mongoid_50.gemfile
  - gemfiles/mongoid_51.gemfile
  - gemfiles/mongoid_master.gemfile
matrix:
  exclude:
    - rvm: "2.1.10"
      gemfile: gemfiles/mongoid_master.gemfile