# frozen_string_literal: true
require 'mongoid'
require 'mongoload/version'
require 'mongoload/auto_include_context'
require 'mongoload/relation_loader'
require 'mongoload/patches/contextual_mongo'
require 'mongoload/patches/document'
require 'mongoload/patches/relations_accessors'
require 'mongoload/patches/relations_targets_enumerable'
require 'mongoload/patches/relations_options'
require 'mongoload/patches/relations_metadata'
